// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2SBtokV0g7F3fFhb1N9lP_VnfLNFPyoM',
    appId: '1:480918231151:web:3a8a537fedb5ebda25959a',
    messagingSenderId: '480918231151',
    projectId: 'wesionary-attendance',
    authDomain: 'wesionary-attendance.firebaseapp.com',
    storageBucket: 'wesionary-attendance.firebasestorage.app',
    measurementId: 'G-VHJTER514G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLVHG77CnS93BJja0h7gY3LIJQGFDh9xY',
    appId: '1:480918231151:android:77f0acbbeab8493c25959a',
    messagingSenderId: '480918231151',
    projectId: 'wesionary-attendance',
    storageBucket: 'wesionary-attendance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6eRtUWHb7aDYre1ihBmO2tIU30SFzapw',
    appId: '1:480918231151:ios:ec5416592212a62325959a',
    messagingSenderId: '480918231151',
    projectId: 'wesionary-attendance',
    storageBucket: 'wesionary-attendance.firebasestorage.app',
    iosBundleId: 'com.wesionaryteam.attendance',
  );
}
